### ISSUE TITLE
When sidebar is place on the left hiding it leaves invisible sidebar still floating on top.

### ISSUE THREAD

**Issue by vonHabsi** [thepante/alfs-firefox#1]
I have discovered a bug when it is placed on the left.

It seems that although hiding it changes the opacity to 0, but does not remove it or relocate it. So when a link on the page underneath it is clicked, the actual item clicked is the item in the sidebar which is at the same position but invisible.

This is evident when you pass the cursor over links where the hidden sidebar is. You will see that the cursor does not change when it passes over a link, and the URL does not display at the bottom of the page.

A more obvious is symptom is that TST displays the contents of a collapsed tree in a popup when the cursor hovers over the tab for a few seconds, meaning that sidebar is still present but only transparent.

The line `alfs.hidden=false` at https://github.com/thepante/alfs-firefox/blob/master/alfs.uc.js#L30 appears to be the culprit, but changing it to `alfs.hidden=true` results in the recreation of the TST contents when it is shown again, so I'm assuming that setting it to `true` destroys the TST contents.

My CSS of knowledge is limited but could the line `margin-right: calc(-100vh * 0.4);` in the `.closeit` CSS be a bug as well?. I don't know much about CSS, but perhaps that code does not allow for the sidebar being on the left.

      .closeit {
          opacity: 0;
          box-shadow: none !important;
          margin-right: calc(-100vh * 0.4);
          transition-property: opacity;
          transition-duration: 0.15s !important;
      }
       
I assume that the negative margin-right value moves it off screen when it is on the right-side, but doesn't work when it is on the left. Perhaps `display: none` may be better?

**Comment by thepante** [comment]
Thanks for report this, now should be fixed. I checked that, and you are right; if sidebar on left, it didn't goes away when "hiding". I updated the .css, this:
```css
margin-right: calc(-100vh * 0.4);
```
As you said, that was the reason of that. 
Instead of moving to the right, now its moving to the top and by more distance:
```css
margin-top: calc(-100vh * 2);
```
----
I did the `alfs.hidden=false` to keep it _active_, so it can be support transitions for a smoothed open/close. If this is hidden with that attribute: it do the change without calculating something from _value A to value B_, instead it just visible disappears instantly. That the same issue when using `display: none`.
Take this comparison: hidden or display attributes are like light switches, on←or→off, but using css to archive that, its like to get a light dimmer.
That's why I keep it that, to be possible to get better open and close effects

**Comment by vonHabsi** [comment]
The problem with the invisible sidebar still responding to clicks has gone.

But there seems to be a new problem. When it is hidden and show again TST recreates its contents and results in the delay before it is ready. It is as though one of the changes you have made triggers an undocumented feature or side effect which causes TST to be recreated.

When I look at the code myself I can't see what causes it. I suspect it may be some undocumented feature of Firefox. I am using Nightly as well and it could be a factor.

**Comment by vonHabsi** [comment]
I switched back to the previous configuration and it seems that the problem of clicking links underneath the hidden sidebar activating those in the sidebar itself is an intermittent one, but at least the delay caused by recreating the TST tab is gone.

I think there are some internal inconsistencies in the underlying Firefox code which triggers it.

In any case the keyboard shortcut to activate it makes all the difference. I have switched to `Ctrl-8` for the time being, but I think `Alt-8` or some function key may be better. It is surprising to see how so many `Ctrl` key combinations have been seized by other desktop and browser functions.

Thanks.

**Comment by thepante** [comment]
Ok, post the code you are actually using to compare the differences. 
Using [margin-top line](https://github.com/thepante/alfs-firefox/blob/master/userChrome.css#L62) should avoid the issue of clicking it while hiding.

---
I was testing the draggable option but was facing some issues:
1. Buggy jumpy dragging
2. When hiding, the issue _invisible but still responding to clicks_ its back

And working on better way to set if attach to left or right, and others things related to that.
