### ISSUE TITLE
Bugs in very simplified version using keyboard for toggling.

### ISSUE THREAD

**Issue by vonHabsi** [thepante/alfs-firefox#4]
I reverted back to an earlier version and make it simple as possible for use with the keyboard. The main difference is to use the `Alt-J` for toggling it.

Here is the Javascript and CSS for them.

Javascript - https://gist.github.com/vonHabsi/57f95e37102b4272a4755392e64ee50e

CSS - https://gist.github.com/vonHabsi/d2c7cbe01bca8cb4c3dbcd97d532f985

Appearance when sidebar is hidden - content is shifted off screen.

What CSS and Javascript is required? Is there some way to check the CSS used in Firefox itself when the sidebar is hidden, then adjust the hiding to match the same CSS? The CSS for displaying it seems perfectly normal

![selection_004](https://user-images.githubusercontent.com/200945/52759023-583d7000-3002-11e9-93a8-065b76530a07.png)

Appearance when sidebar is displayed, it appear normal.
![selection_003](https://user-images.githubusercontent.com/200945/52759012-52e02580-3002-11e9-8704-aa7b11649050.png)

**Comment by thepante** [comment]
I hope soon can have time and will clean my code, its quite messy and it can get broke pretty easily when taking-off some part from it. 

---
Here you go, I tested your files in a fresh profile. Only adjusted the js, working good:
```javascript
// ==UserScript==
// @name           userChrome.js
// @include        main
// @version        0.8.1.vH
// @note           u/thepante
// ==/UserScript==

document.getElementById("sidebar").src='chrome://browser/content/webext-panels.xul';
document.getElementById("sidebar-button").checked=false;
var alfs = document.getElementById("sidebar-box");
var ogclass = alfs.className;
var statbnt = 0;

alfs.checked=true;
setTimeout(function(e) {alfs.setAttribute("hidden", "true");}, 500);
alfs.className = ogclass + ' closeit';

document.getElementById("sidebar-button").addEventListener('click', function(e){
	event.preventDefault();
	doitmf();
});


/* Alt-Char */
/* a = 65, 0 = 48 */
document.onkeyup = function(e) {
  if (e.altKey && e.which == 74) {
    doitmf();
  } 
};



function doitmf() {
  if (statbnt == 0) {
        console.log(statbnt+" : alfs open");
        document.getElementById("sidebar-button").checked=true;
        alfs.className = ogclass + ' openit';
        alfs.hidden=false;
        statbnt = 1;
    }
    else {
        console.log(statbnt+" : alfs close");
        document.getElementById("sidebar-button").checked=false;
        alfs.className = ogclass + ' closeit';
        alfs.hidden=true;
        statbnt = 0;
    }
}

```

**Comment by thepante** [comment]
For inspect the Firefox UI: https://developer.mozilla.org/en-US/docs/Tools/Browser_Toolbox

**Comment by vonHabsi** [comment]
In fact I managed to activate the Developer Tools from the browser itself via the pinned thread at r/FirefoxCSS, [Tutorial: How to create and live-debug userChrome.css](https://old.reddit.com/r/FirefoxCSS/comments/73dvty/tutorial_how_to_create_and_livedebug_userchromecss/).

After a bit of investigation simply changing the CSS for `.closeit` to

```
.closeit {
      display:none;
}
```
fixes the problem.

I don't know if there are may be some unwanted side-effects but so far it has been adequate.
Since the keyboard logic is concerned with simply replicating the standard behaviour of the sidebar-button it is probably enough.

**Comment by vonHabsi** [comment]
I have had it working the way I want for some time so I am closing all these issues
